//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramModulesDevelopmentKursovik.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int catitems_id { get; set; }
        public int quantity { get; set; }
    
        public virtual CatItems CatItems { get; set; }
        public virtual Users Users { get; set; }
    }
}
