//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramModulesDevelopmentKursovik.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime datefrom { get; set; }
        public string dateopen
        {
            get
            {
                return datefrom.Date.ToString("d");
            }
        }
        public Nullable<System.DateTime> dateto { get; set; }
        public string dateclose
        {
            get
            {
                if (dateto != null)
                    return dateto?.Date.ToString("d");
                else 
                    return null;
            }
        }
        public string userinfo
        {
            get
            {
                return this.Users.name + " " + this.Users.patronymic + " " + this.Users.surname + " [" + this.Users.email + "]";
            }
        }
        public int user_id { get; set; }
        public int donestate_id { get; set; }
        public int paymentstate_id { get; set; }
    
        public virtual DoneStates DoneStates { get; set; }
        public virtual PaymentStates PaymentStates { get; set; }
        public virtual Users Users { get; set; }
    }
}
