//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramModulesDevelopmentKursovik.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersItems
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int catitems_id { get; set; }
        public int quantity { get; set; }
    
        public virtual CatItems CatItems { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
