//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramModulesDevelopmentKursovik.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime datefrom { get; set; }
        public System.DateTime dateto { get; set; }
        public int user_id { get; set; }
        public int donestate_id { get; set; }
        public int paymentstate_id { get; set; }
    
        public virtual DoneStates DoneStates { get; set; }
        public virtual PaymentState PaymentState { get; set; }
        public virtual Users Users { get; set; }
    }
}
